name: 'Workflow Concurrency'
description: 'Control the concurrency of your GitHub Workflows Runs'
author: 'Mark Massoud'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'shuffle'
  color: 'green'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
